services:

  postgres:
    image: postgres:15
    container_name: quantum_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: security_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: quantum_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: quantum_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: quantum_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

  redis:
    image: redis:7
    container_name: quantum_redis
    ports:
      - "6379:6379"


  quantum_kafka:
    image: apache/kafka:3.7.0
    container_name: quantum_kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 9riA7JQ7T2O2CfJPV4tvug
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@quantum_kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  # masscan:
  #  image: quantum_masscan
  #  container_name: quantum_masscan
  #  network_mode: host

  zgrab:
    image: ghcr.io/zmap/zgrab2
    container_name: quantum_zgrab

  openssl:
    image: frapsoft/openssl
    container_name: quantum_openssl
        
volumes:
  postgres_data: