-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ai_agent_results
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    scan_id uuid,
    asset_id uuid NOT NULL,
    agent_name text COLLATE pg_catalog."default" NOT NULL,
    result_type text COLLATE pg_catalog."default" NOT NULL,
    severity text COLLATE pg_catalog."default",
    confidence double precision,
    result_data jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_agent_results_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alert_events
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    alert_id uuid NOT NULL,
    event_source text COLLATE pg_catalog."default",
    event_data jsonb,
    "timestamp" timestamp without time zone,
    CONSTRAINT alert_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.alerts
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    severity text COLLATE pg_catalog."default",
    alert_type text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    CONSTRAINT alerts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.api_endpoints
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    endpoint_path text COLLATE pg_catalog."default",
    method text COLLATE pg_catalog."default",
    auth_type text COLLATE pg_catalog."default",
    CONSTRAINT api_endpoints_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.api_keys
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    api_key text COLLATE pg_catalog."default",
    permissions text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT api_keys_pkey PRIMARY KEY (id),
    CONSTRAINT api_keys_api_key_key UNIQUE (api_key)
);

CREATE TABLE IF NOT EXISTS public.api_services
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    service_name text COLLATE pg_catalog."default",
    version text COLLATE pg_catalog."default",
    CONSTRAINT api_services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_fingerprints
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    asset_id uuid NOT NULL,
    hosting_provider text COLLATE pg_catalog."default",
    cloud_provider text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    web_server text COLLATE pg_catalog."default",
    backend_stack text COLLATE pg_catalog."default",
    framework text COLLATE pg_catalog."default",
    cms text COLLATE pg_catalog."default",
    waf_cdn text COLLATE pg_catalog."default",
    dns_provider text COLLATE pg_catalog."default",
    email_provider text COLLATE pg_catalog."default",
    load_balancer text COLLATE pg_catalog."default",
    os_hint text COLLATE pg_catalog."default",
    deployment_type text COLLATE pg_catalog."default",
    reverse_dns text COLLATE pg_catalog."default",
    asn text COLLATE pg_catalog."default",
    org_name text COLLATE pg_catalog."default",
    confidence_score double precision,
    raw_headers jsonb,
    raw_dns jsonb,
    raw_tls jsonb,
    raw_whois jsonb,
    detected_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    web_server_detection_method text COLLATE pg_catalog."default",
    web_server_candidates jsonb,
    passive_technology_matches jsonb,
    http_observations jsonb,
    favicon_hash jsonb,
    behavioral_fingerprint jsonb,
    evidence_summary jsonb,
    external_exposure_summary jsonb,
    CONSTRAINT asset_fingerprints_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_metadata
(
    asset_id uuid NOT NULL,
    owner_team text COLLATE pg_catalog."default",
    environment text COLLATE pg_catalog."default",
    cloud_provider text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    CONSTRAINT asset_metadata_pkey PRIMARY KEY (asset_id)
);

CREATE TABLE IF NOT EXISTS public.asset_registry
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    asset_identifier text COLLATE pg_catalog."default",
    asset_type text COLLATE pg_catalog."default",
    first_seen timestamp without time zone,
    last_seen timestamp without time zone,
    status text COLLATE pg_catalog."default",
    criticality text COLLATE pg_catalog."default",
    CONSTRAINT asset_registry_pkey PRIMARY KEY (id),
    CONSTRAINT unique_asset_identifier UNIQUE (asset_identifier)
);

CREATE TABLE IF NOT EXISTS public.asset_risk_scores
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    score integer,
    risk_category text COLLATE pg_catalog."default",
    CONSTRAINT asset_risk_scores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_tags
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    tag text COLLATE pg_catalog."default",
    CONSTRAINT asset_tags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.asset_vulnerabilities
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    snapshot_id uuid NOT NULL,
    vulnerability_id uuid NOT NULL,
    CONSTRAINT asset_vulnerabilities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    action text COLLATE pg_catalog."default",
    resource text COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cbom_inventory
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    tls_version text COLLATE pg_catalog."default",
    cipher_suite text COLLATE pg_catalog."default",
    key_exchange text COLLATE pg_catalog."default",
    certificate_id uuid,
    quantum_risk text COLLATE pg_catalog."default",
    CONSTRAINT cbom_inventory_pkey PRIMARY KEY (id),
    CONSTRAINT unique_cbom_asset UNIQUE (asset_id)
);

CREATE TABLE IF NOT EXISTS public.certificates
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    issuer text COLLATE pg_catalog."default",
    subject text COLLATE pg_catalog."default",
    signature_algorithm text COLLATE pg_catalog."default",
    key_size integer,
    expiry_date date,
    CONSTRAINT certificates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cloud_accounts
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    cloud_provider text COLLATE pg_catalog."default",
    account_id text COLLATE pg_catalog."default",
    CONSTRAINT cloud_accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cloud_assets
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    cloud_account_id uuid NOT NULL,
    resource_id text COLLATE pg_catalog."default",
    resource_type text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    CONSTRAINT cloud_assets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.compliance_reports
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid,
    report_type text COLLATE pg_catalog."default",
    generated_at timestamp without time zone,
    CONSTRAINT compliance_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dns_records
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    subdomain_id uuid NOT NULL,
    record_type text COLLATE pg_catalog."default",
    value text COLLATE pg_catalog."default",
    ttl integer,
    CONSTRAINT dns_records_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.domains
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    domain_name text COLLATE pg_catalog."default",
    CONSTRAINT domains_pkey PRIMARY KEY (id),
    CONSTRAINT domains_domain_name_key UNIQUE (domain_name)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'employee'::character varying,
    department character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "position" character varying(100) COLLATE pg_catalog."default",
    location character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    join_date date,
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT unique_employee_email_per_company UNIQUE (organization_id, email)
);

CREATE TABLE IF NOT EXISTS public.event_stream
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    event_type text COLLATE pg_catalog."default",
    payload jsonb,
    created_at timestamp without time zone,
    CONSTRAINT event_stream_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.organizations
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    industry character varying(100) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.port_scan_results
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    port integer,
    protocol text COLLATE pg_catalog."default",
    state text COLLATE pg_catalog."default",
    scan_time timestamp without time zone,
    CONSTRAINT port_scan_results_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pqc_analysis
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    algorithm text COLLATE pg_catalog."default",
    pqc_ready boolean,
    recommended_upgrade text COLLATE pg_catalog."default",
    CONSTRAINT pqc_analysis_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.risk_model_features
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    feature_name text COLLATE pg_catalog."default",
    feature_value double precision,
    CONSTRAINT risk_model_features_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.risk_predictions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    model_version text COLLATE pg_catalog."default",
    predicted_risk double precision,
    confidence double precision,
    CONSTRAINT risk_predictions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.risk_scores
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    score integer,
    risk_level text COLLATE pg_catalog."default",
    calculated_at timestamp without time zone,
    CONSTRAINT risk_scores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scan_checkpoints
(
    scan_id uuid NOT NULL,
    stage text COLLATE pg_catalog."default",
    last_asset text COLLATE pg_catalog."default",
    last_event text COLLATE pg_catalog."default",
    meta jsonb,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT scan_checkpoints_pkey PRIMARY KEY (scan_id)
);

CREATE TABLE IF NOT EXISTS public.scan_deltas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    previous_snapshot uuid,
    current_snapshot uuid,
    change_type text COLLATE pg_catalog."default",
    change_description text COLLATE pg_catalog."default",
    CONSTRAINT scan_deltas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scan_events
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    scan_id uuid NOT NULL,
    event_type text COLLATE pg_catalog."default",
    event_data jsonb,
    "timestamp" timestamp without time zone,
    CONSTRAINT scan_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scan_jobs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    scan_type text COLLATE pg_catalog."default",
    trigger text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    started_at timestamp without time zone,
    finished_at timestamp without time zone,
    domain text COLLATE pg_catalog."default",
    CONSTRAINT scan_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scan_snapshots
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    scan_id uuid NOT NULL,
    asset_id uuid NOT NULL,
    snapshot_time timestamp without time zone,
    CONSTRAINT scan_snapshots_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subdomains
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    domain_id uuid NOT NULL,
    subdomain text COLLATE pg_catalog."default",
    ip_address inet,
    last_seen timestamp without time zone,
    CONSTRAINT subdomains_pkey PRIMARY KEY (id),
    CONSTRAINT unique_subdomain UNIQUE (subdomain)
);

CREATE TABLE IF NOT EXISTS public.tls_scan_results
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    asset_id uuid NOT NULL,
    tls_version text COLLATE pg_catalog."default",
    cipher_suite text COLLATE pg_catalog."default",
    key_exchange text COLLATE pg_catalog."default",
    forward_secrecy boolean,
    scan_time timestamp without time zone,
    CONSTRAINT tls_scan_results_pkey PRIMARY KEY (id),
    CONSTRAINT unique_tls_asset UNIQUE (asset_id)
);

CREATE TABLE IF NOT EXISTS public.topology_edges
(
    source_node uuid,
    target_node uuid,
    relation_type text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.topology_nodes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    node_type text COLLATE pg_catalog."default",
    value text COLLATE pg_catalog."default",
    CONSTRAINT topology_nodes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    organization_id uuid NOT NULL,
    name character varying(200) COLLATE pg_catalog."default",
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vulnerabilities
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    cve_id text COLLATE pg_catalog."default",
    severity text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    published_date date,
    CONSTRAINT vulnerabilities_pkey PRIMARY KEY (id),
    CONSTRAINT vulnerabilities_cve_id_key UNIQUE (cve_id)
);

ALTER TABLE IF EXISTS public.ai_agent_results
    ADD CONSTRAINT ai_agent_results_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ai_agent_results_asset_id
    ON public.ai_agent_results(asset_id);


ALTER TABLE IF EXISTS public.ai_agent_results
    ADD CONSTRAINT ai_agent_results_scan_id_fkey FOREIGN KEY (scan_id)
    REFERENCES public.scan_jobs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ai_agent_results_scan_id
    ON public.ai_agent_results(scan_id);


ALTER TABLE IF EXISTS public.alert_events
    ADD CONSTRAINT alert_events_alert_id_fkey FOREIGN KEY (alert_id)
    REFERENCES public.alerts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.alerts
    ADD CONSTRAINT alerts_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_alert_asset
    ON public.alerts(asset_id);


ALTER TABLE IF EXISTS public.api_endpoints
    ADD CONSTRAINT api_endpoints_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.api_keys
    ADD CONSTRAINT api_keys_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.api_services
    ADD CONSTRAINT api_services_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.asset_fingerprints
    ADD CONSTRAINT asset_fingerprints_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_asset_fingerprint_asset
    ON public.asset_fingerprints(asset_id);


ALTER TABLE IF EXISTS public.asset_metadata
    ADD CONSTRAINT asset_metadata_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS asset_metadata_pkey
    ON public.asset_metadata(asset_id);


ALTER TABLE IF EXISTS public.asset_registry
    ADD CONSTRAINT asset_registry_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_asset_org
    ON public.asset_registry(organization_id);


ALTER TABLE IF EXISTS public.asset_risk_scores
    ADD CONSTRAINT asset_risk_scores_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.asset_tags
    ADD CONSTRAINT asset_tags_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.asset_vulnerabilities
    ADD CONSTRAINT asset_vulnerabilities_snapshot_id_fkey FOREIGN KEY (snapshot_id)
    REFERENCES public.scan_snapshots (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_vuln_snapshot
    ON public.asset_vulnerabilities(snapshot_id);


ALTER TABLE IF EXISTS public.asset_vulnerabilities
    ADD CONSTRAINT asset_vulnerabilities_vulnerability_id_fkey FOREIGN KEY (vulnerability_id)
    REFERENCES public.vulnerabilities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cbom_inventory
    ADD CONSTRAINT cbom_inventory_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS unique_cbom_asset
    ON public.cbom_inventory(asset_id);


ALTER TABLE IF EXISTS public.cbom_inventory
    ADD CONSTRAINT cbom_inventory_certificate_id_fkey FOREIGN KEY (certificate_id)
    REFERENCES public.certificates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.certificates
    ADD CONSTRAINT certificates_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cloud_accounts
    ADD CONSTRAINT cloud_accounts_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cloud_assets
    ADD CONSTRAINT cloud_assets_cloud_account_id_fkey FOREIGN KEY (cloud_account_id)
    REFERENCES public.cloud_accounts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.compliance_reports
    ADD CONSTRAINT compliance_reports_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dns_records
    ADD CONSTRAINT dns_records_subdomain_id_fkey FOREIGN KEY (subdomain_id)
    REFERENCES public.subdomains (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.domains
    ADD CONSTRAINT domains_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT fk_employee_org FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.port_scan_results
    ADD CONSTRAINT port_scan_results_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_port_asset
    ON public.port_scan_results(asset_id);


ALTER TABLE IF EXISTS public.pqc_analysis
    ADD CONSTRAINT pqc_analysis_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.risk_model_features
    ADD CONSTRAINT risk_model_features_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.risk_predictions
    ADD CONSTRAINT risk_predictions_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.risk_scores
    ADD CONSTRAINT risk_scores_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.scan_deltas
    ADD CONSTRAINT scan_deltas_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.scan_deltas
    ADD CONSTRAINT scan_deltas_current_snapshot_fkey FOREIGN KEY (current_snapshot)
    REFERENCES public.scan_snapshots (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.scan_deltas
    ADD CONSTRAINT scan_deltas_previous_snapshot_fkey FOREIGN KEY (previous_snapshot)
    REFERENCES public.scan_snapshots (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.scan_events
    ADD CONSTRAINT scan_events_scan_id_fkey FOREIGN KEY (scan_id)
    REFERENCES public.scan_jobs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.scan_jobs
    ADD CONSTRAINT scan_jobs_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.scan_snapshots
    ADD CONSTRAINT scan_snapshots_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_scan_asset
    ON public.scan_snapshots(asset_id);


ALTER TABLE IF EXISTS public.scan_snapshots
    ADD CONSTRAINT scan_snapshots_scan_id_fkey FOREIGN KEY (scan_id)
    REFERENCES public.scan_jobs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subdomains
    ADD CONSTRAINT subdomains_domain_id_fkey FOREIGN KEY (domain_id)
    REFERENCES public.domains (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tls_scan_results
    ADD CONSTRAINT tls_scan_results_asset_id_fkey FOREIGN KEY (asset_id)
    REFERENCES public.asset_registry (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tls_asset
    ON public.tls_scan_results(asset_id);


ALTER TABLE IF EXISTS public.topology_edges
    ADD CONSTRAINT topology_edges_source_node_fkey FOREIGN KEY (source_node)
    REFERENCES public.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.topology_edges
    ADD CONSTRAINT topology_edges_target_node_fkey FOREIGN KEY (target_node)
    REFERENCES public.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;